<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call([
            RoleSeeder::class,
            UserSeeder::class,
        ]);

        // 2. Seed SCM Contracts
        DB::table('scm')->insert([
            [
                'id' => 1,
                'nomor' => '012/PGE-LHD/BS/2025',
                'nama' => 'Penyediaan Jasa Pengemudi Operasional Area Lahendong',
                'vendor' => 'PT Kawanua Multi Mandiri',
                'nilai' => 1200000000,
                'mulai' => '2025-01-01',
                'selesai' => '2026-12-31',
                'progres' => 75,
                'status' => 'Aktif',
                'fungsi' => 'BS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nomor' => '034/PGE-LHD/SCM/2026',
                'nama' => 'Pengadaan Carbon Steel Pipe 6 Inch Sch 80',
                'vendor' => 'PT Pertamina Drilling Services Indonesia',
                'nilai' => 850000000,
                'mulai' => '2026-02-15',
                'selesai' => '2026-08-15',
                'progres' => 40,
                'status' => 'Aktif',
                'fungsi' => 'SCM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nomor' => '056/PGE-LHD/MTC/2025',
                'nama' => 'Jasa Pemeliharaan Rutin Turbine & Generator Unit 5 & 6',
                'vendor' => 'PT Fuji Electric Indonesia',
                'nilai' => 4500000000,
                'mulai' => '2025-03-01',
                'selesai' => '2026-03-01',
                'progres' => 100,
                'status' => 'Selesai',
                'fungsi' => 'MTC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nomor' => '078/PGE-LHD/HSSE/2026',
                'nama' => 'Pekerjaan Pemasangan Fire Hydrant System Gedung Kantor',
                'vendor' => 'PT Mitra Proteksi Manado',
                'nilai' => 600000000,
                'mulai' => '2026-04-01',
                'selesai' => '2026-10-01',
                'progres' => 20,
                'status' => 'Kritis',
                'fungsi' => 'HSSE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nomor' => '089/PGE-LHD/BS/2026',
                'nama' => 'Sewa Kendaraan Penunjang Operasional PGE Lahendong',
                'vendor' => 'PT Trans Kawanua Rentcar',
                'nilai' => 1450000000,
                'mulai' => '2026-01-01',
                'selesai' => '2026-12-31',
                'progres' => 50,
                'status' => 'Amandemen',
                'fungsi' => 'BS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 3. Seed MOM
        DB::table('mom')->insert([
            [
                'id' => 1,
                'fungsi' => 'MTC',
                'isu' => 'Turn Around Unit 5&6',
                'tindak_lanjut' => 'KOM di W2 Juli (Logistik Support)',
                'status' => 'On Progress',
                'statusColor' => 'bg-yellow-100 text-yellow-800',
                'feedback' => 'Koordinasikan dengan Logistik untuk ketersediaan sparepart kritikal sebelum TA dimulai. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'fungsi' => 'BS',
                'isu' => 'Pengajuan ABI 2027',
                'tindak_lanjut' => 'Menunggu input MTC & HSSE',
                'status' => 'Pending Input',
                'statusColor' => 'bg-red-100 text-red-800',
                'feedback' => 'Perlu review anggaran lebih lanjut sebelum pengajuan. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'fungsi' => 'SCM',
                'isu' => 'Fitting Drip Pot',
                'tindak_lanjut' => 'Nego vendor selesai, deltime 8 week',
                'status' => 'Selesai',
                'statusColor' => 'bg-green-100 text-green-800',
                'feedback' => 'Nego harga sudah oke. Monitor ketat lead time pengiriman material agar tidak mengganggu operasional. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'fungsi' => 'HC',
                'isu' => 'Penyelarasan Data Pensiun Batas Usia 56',
                'tindak_lanjut' => 'Penyelarasan data profil karyawan organik dan TAD',
                'status' => 'Selesai',
                'statusColor' => 'bg-green-100 text-green-800',
                'feedback' => 'Sudah diverifikasi. Pastikan data pensiun terproyeksi dengan akurat untuk 3 tahun ke depan. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'fungsi' => 'LOG',
                'isu' => 'Audit Fisik Stock Material',
                'tindak_lanjut' => 'Pengecekan saldo Gate Valve di Gudang Utama',
                'status' => 'On Progress',
                'statusColor' => 'bg-yellow-100 text-yellow-800',
                'feedback' => 'Segera tindak lanjuti jika terdapat selisih fisik dengan pencatatan sistem. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'fungsi' => 'IT',
                'isu' => 'Pembaruan Lisensi Server DCS',
                'tindak_lanjut' => 'Pengajuan anggaran perpanjangan lisensi tahunan',
                'status' => 'Pending Input',
                'statusColor' => 'bg-red-100 text-red-800',
                'feedback' => 'Lisensi ini kritikal untuk operasional plant. Prioritaskan pengajuannya minggu ini. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'fungsi' => 'BUDGET',
                'isu' => 'Realisasi Anggaran Perjalanan Dinas (ABO)',
                'tindak_lanjut' => 'Penyesuaian budget dengan aktual pengeluaran kuartal 1',
                'status' => 'Menunggu Review',
                'statusColor' => 'bg-yellow-100 text-yellow-800',
                'feedback' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'fungsi' => 'ARSIP',
                'isu' => 'Digitalisasi Dokumen Kontrak Lama',
                'tindak_lanjut' => 'Pemindaian 200 dokumen fisik dari gudang arsip',
                'status' => 'On Progress',
                'statusColor' => 'bg-yellow-100 text-yellow-800',
                'feedback' => 'Tolong prioritaskan dokumen kontrak sebelum tahun 2023. - Pak Budi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 4. Seed Calendar Events
        DB::table('calendar_events')->insert([
            [
                'id' => 1,
                'title' => 'Rapat RKAP & ABI 2027',
                'date' => '2026-06-28',
                'category' => 'BS',
                'description' => 'Pembahasan rencana anggaran ABI 2027 bersama divisi MTC.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Review Kontrak Driver Operasional',
                'date' => '2026-06-30',
                'category' => 'SCM',
                'description' => 'Review progress kontrak PT Kawanua Multi Mandiri.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Mutasi & Promosi Tahap I',
                'date' => '2026-07-02',
                'category' => 'HC',
                'description' => 'Ploting karyawan mutasi di Area Lahendong.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Stock Opname Semesteran',
                'date' => '2026-07-05',
                'category' => 'LOG',
                'description' => 'Pengecekan fisik material di gudang utama.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'Server Maintenance & Update',
                'date' => '2026-07-10',
                'category' => 'IT',
                'description' => 'Rutinitas backup database dan update patches server lokal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 5. Seed HC Mutations
        DB::table('hc_mutations')->insert([
            [
                'id' => 1,
                'bulan' => 'Mei 2026',
                'nama' => 'Andi Wijaya',
                'jenis' => 'Masuk',
                'fungsi' => 'MTC / Engineer Area',
                'keterangan' => 'Mutasi dari Area Kamojang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'bulan' => 'Mei 2026',
                'nama' => 'Rudi Hermawan',
                'jenis' => 'Keluar',
                'fungsi' => 'OP / Operator Control Room',
                'keterangan' => 'Pensiun Normal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'bulan' => 'April 2026',
                'nama' => 'Siti Rahma',
                'jenis' => 'Masuk',
                'fungsi' => 'BS / Finance Analyst',
                'keterangan' => 'Karyawan Baru Rekrutmen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'bulan' => 'Maret 2026',
                'nama' => 'Ferry K.',
                'jenis' => 'Keluar',
                'fungsi' => 'SCM / Buyer',
                'keterangan' => 'Mutasi ke Kantor Pusat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 6. Seed HC TAD Workers
        DB::table('hc_tad')->insert([
            [
                'id' => 1,
                'nama' => 'Joko Susilo',
                'peran' => 'Driver Operasional',
                'vendor' => 'PT Kawanua Multi Mandiri',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nama' => 'Nancy Pangemanan',
                'peran' => 'Admin Support BS',
                'vendor' => 'PT Trans Kawanua Rentcar',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nama' => 'Tono Sumarjo',
                'peran' => 'Security Guard Cluster 4',
                'vendor' => 'PT Garda Utama Manado',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nama' => 'Meike Tumewu',
                'peran' => 'Catering Service BS',
                'vendor' => 'PT Minahasa Boga Rasa',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 7. Seed HC Retired
        DB::table('hc_retired')->insert([
            [
                'id' => 1,
                'nama' => 'Budi Santoso',
                'jabatan' => 'Manager Area Lahendong',
                'tahun' => 2026,
                'tanggal' => '2026-05-01',
                'keterangan' => 'Pensiun Normal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nama' => 'Bambang Sudarsono',
                'jabatan' => 'Supervisor Maintenance Unit 5',
                'tahun' => 2025,
                'tanggal' => '2025-11-15',
                'keterangan' => 'Pensiun Normal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nama' => 'Hanny Lumentut',
                'jabatan' => 'Senior Staff SCM & Procurement',
                'tahun' => 2024,
                'tanggal' => '2024-08-01',
                'keterangan' => 'Pensiun Dini',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nama' => 'Wayan Sastrawan',
                'jabatan' => 'Operator Utama Sumur Kluster',
                'tahun' => 2024,
                'tanggal' => '2024-03-10',
                'keterangan' => 'Pensiun Normal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 8. Seed Alat Berat
        DB::table('alat_berat')->insert([
            [
                'id' => 1,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'CRANE 30T',
                'alokasi' => 'LHD-3',
                'merk' => 'TADANO',
                'model' => 'GR300E-3',
                'stnk' => '2027-08-30',
                'pajak' => '2026-08-30',
                'kir' => '2026-08-13',
                'status' => 'AMAN',
                'kondisi' => 'Under Maintenance: Sparepart dari UT (piping brake) estimasi ready akhir agustus 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'TMC 10T',
                'alokasi' => 'LHD-3',
                'merk' => 'TADANO',
                'model' => 'TM-ZT1000',
                'stnk' => '2027-08-30',
                'pajak' => '2026-08-30',
                'kir' => '2026-08-13',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nopol' => 'DB 8273 GY',
                'tahun' => '-',
                'jenis' => 'TMC 3.5T',
                'alokasi' => 'LHD-3',
                'merk' => 'TADANO',
                'model' => 'TM-ZT630',
                'stnk' => '2027-08-30',
                'pajak' => '2026-08-30',
                'kir' => '2026-08-13',
                'status' => 'AMAN',
                'kondisi' => 'Under Maintenance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'FORKLIFT 7T',
                'alokasi' => 'LHD-2',
                'merk' => 'CATERPILLAR',
                'model' => 'DP70',
                'stnk' => '-',
                'pajak' => '-',
                'kir' => '-',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'FORKLIFT 5T',
                'alokasi' => 'LHD-3',
                'merk' => 'CATERPILLAR',
                'model' => 'DP50',
                'stnk' => '-',
                'pajak' => '-',
                'kir' => '-',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'FORKLIFT 4T',
                'alokasi' => 'LHD-3',
                'merk' => 'CATERPILLAR',
                'model' => 'DP40',
                'stnk' => '-',
                'pajak' => '-',
                'kir' => '-',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'FORKLIFT 3.5T',
                'alokasi' => 'LHD-4',
                'merk' => 'CATERPILLAR',
                'model' => 'DP35',
                'stnk' => '-',
                'pajak' => '-',
                'kir' => '-',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nopol' => '-',
                'tahun' => '-',
                'jenis' => 'FORKLIFT 2.5T',
                'alokasi' => 'LHD-3',
                'merk' => 'CATERPILLAR',
                'model' => 'DP25',
                'stnk' => '-',
                'pajak' => '-',
                'kir' => '-',
                'status' => 'AMAN',
                'kondisi' => 'Baik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 9. Seed Perbaikan
        DB::table('perbaikan')->insert([
            [
                'id' => 1,
                'lokasi' => 'Rumah Dinas No. 12',
                'pekerjaan' => 'Perbaikan Atap dan Plafon Bocor',
                'estimasi' => 25000000,
                'realisasi' => 24500000,
                'status' => 'Selesai',
                'keterangan' => 'Pekerjaan selesai 100% menggunakan dana rutin LOG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'lokasi' => 'Gedung Kantor Utama',
                'pekerjaan' => 'Pengecatan dan Perbaikan Fasad Depan',
                'estimasi' => 45000000,
                'realisasi' => 38000000,
                'status' => 'On Progress',
                'keterangan' => 'Progres fisik 75%, estimasi selesai Juli 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'lokasi' => 'Rumah Dinas No. 5',
                'pekerjaan' => 'Renovasi Pagar Keliling',
                'estimasi' => 15000000,
                'realisasi' => 15000000,
                'status' => 'Selesai',
                'keterangan' => 'Selesai tepat waktu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'lokasi' => 'Gedung Kantor SCM',
                'pekerjaan' => 'Instalasi AC Cassette 3 PK',
                'estimasi' => 18000000,
                'realisasi' => 18000000,
                'status' => 'Selesai',
                'keterangan' => 'AC Ruang Buyer SCM baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 10. Seed Lembur TAD
        DB::table('lembur_tad')->insert([
            [
                'id' => 1,
                'nopok' => 'M343-250714',
                'nama' => 'Abdulrahman Masriento',
                'jabatan' => 'Pembantu Wisma/Kantor',
                'fungsi' => 'BUSINESS SUPPORT',
                'upah' => 4248000,
                'jamLembur' => 2.0,
                'lemburVal' => 90516,
                'periode' => 'Mei 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nopok' => 'M343-250715',
                'nama' => 'Amelia Ibrahim',
                'jabatan' => 'Pemuka Wisma/Kantor',
                'fungsi' => 'BUSINESS SUPPORT',
                'upah' => 4478000,
                'jamLembur' => 38.0,
                'lemburVal' => 1164996,
                'periode' => 'Mei 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nopok' => 'M343-250700',
                'nama' => 'Asep Fudy Juliansyah',
                'jabatan' => 'Pembantu Wisma/Kantor',
                'fungsi' => 'BUSINESS SUPPORT',
                'upah' => 4248000,
                'jamLembur' => 58.0,
                'lemburVal' => 2624999,
                'periode' => 'Mei 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nopok' => 'M343-250710',
                'nama' => 'Erian Dyon Orah',
                'jabatan' => 'Pembantu Wisma/Kantor',
                'fungsi' => 'BUSINESS SUPPORT',
                'upah' => 4320000,
                'jamLembur' => 18.0,
                'lemburVal' => 762205,
                'periode' => 'Mei 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nopok' => 'M343-250704',
                'nama' => 'Grasela Anggreini Rumengan',
                'jabatan' => 'Pembantu Wisma/Kantor',
                'fungsi' => 'BUSINESS SUPPORT',
                'upah' => 4410000,
                'jamLembur' => 2.0,
                'lemburVal' => 88220,
                'periode' => 'Mei 2026',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 11. Seed Budget Details
        DB::table('budget_details')->insert([
            [
                'id' => 1,
                'fundCent' => 'C0211001',
                'name' => 'Ops. LHD Overhead',
                'commitItem' => '6001006120',
                'text' => 'EMPLOYEE TRAVEL EXPE',
                'budget' => 780000000,
                'consumed' => 214818997,
                'actual' => 214818997,
                'available' => 565181003,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'fundCent' => 'C0211002',
                'name' => 'Ops. LHD Joint Cost',
                'commitItem' => '6000003100',
                'text' => 'G&G REGIONAL SURVEY',
                'budget' => 39277323,
                'consumed' => 29260000,
                'actual' => 29260000,
                'available' => 10017323,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'fundCent' => 'C0211002',
                'name' => 'Ops. LHD Joint Cost',
                'commitItem' => '6001008100',
                'text' => 'EMPLOYEE TRAVEL EXPE',
                'budget' => 350000000,
                'consumed' => 211338746,
                'actual' => 188350941,
                'available' => 138661254,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'fundCent' => 'C0211002',
                'name' => 'Ops. LHD Joint Cost',
                'commitItem' => '6001013210',
                'text' => 'PAINTS, OILS, & LABS',
                'budget' => 440000000,
                'consumed' => 32397000,
                'actual' => 32397000,
                'available' => 407603000,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'fundCent' => 'C0211003',
                'name' => 'Ops. LHD Steam',
                'commitItem' => '6001008100',
                'text' => 'EMPLOYEE TRAVEL EXPE',
                'budget' => 360000000,
                'consumed' => 107004470,
                'actual' => 95910727,
                'available' => 252995530,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'fundCent' => 'C0211004',
                'name' => 'Ops. LHD Steam Maint',
                'commitItem' => '6001009000',
                'text' => 'TURBINE OVERHAUL OUTSOURCING',
                'budget' => 50000000000,
                'consumed' => 44639262335,
                'actual' => 44639262335,
                'available' => 5360737665,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'fundCent' => 'C0211005',
                'name' => 'Ops. LHD Overhead Res',
                'commitItem' => '6001009999',
                'text' => 'OPERATIONAL RESERVE FUNDS',
                'budget' => 68030722677,
                'consumed' => 0,
                'actual' => 0,
                'available' => 68030722677,
                'kategori' => 'ABO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'fundCent' => 'I0211001',
                'name' => 'Investasi Drill LHD-5',
                'commitItem' => '7001002000',
                'text' => 'DRILLING WELL PROJECT Q2',
                'budget' => 12500000000,
                'consumed' => 12500000000,
                'actual' => 12500000000,
                'available' => 0,
                'kategori' => 'ABI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'fundCent' => 'I0211002',
                'name' => 'Investasi Pipe Clust 4',
                'commitItem' => '7001003000',
                'text' => 'CAPITAL PIPING SYSTEM',
                'budget' => 37500000000,
                'consumed' => 0,
                'actual' => 0,
                'available' => 37500000000,
                'kategori' => 'ABI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 12. Seed Stok
        DB::table('stok')->insert([
            [
                'id' => 1,
                'nama' => 'Pipa Besi Carbon 6 Inch Sch 80',
                'fungsi' => 'Maintenance (MTC)',
                'masuk' => 50,
                'keluar' => 20,
                'saldo' => 130,
                'status' => 'Aman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nama' => 'Kabel Power NYY 4x10mm',
                'fungsi' => 'IT / Operations (OP)',
                'masuk' => 1000,
                'keluar' => 300,
                'saldo' => 1200,
                'status' => 'Aman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nama' => 'Valve Gate 4 Inch ANSI 300',
                'fungsi' => 'Maintenance (MTC)',
                'masuk' => 2,
                'keluar' => 6,
                'saldo' => 3,
                'status' => 'Minimum Stock',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nama' => 'O-Ring Gasket Kit 2 Inch',
                'fungsi' => 'Maintenance (MTC)',
                'masuk' => 15,
                'keluar' => 12,
                'saldo' => 18,
                'status' => 'Aman',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 13. Seed Assets (IT Assets)
        DB::table('assets')->insert([
            [
                'id' => 1,
                'nama' => 'Server Utama Cluster 4',
                'kategori' => 'Server & Rack',
                'brand' => 'HPE ProLiant DL380 Gen10',
                'serial' => 'SGH9456XYZ',
                'status' => 'Optimal',
                'lokasi' => 'Ruang Server Kantor Area',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nama' => 'PC Operator Control Room Unit 5',
                'kategori' => 'Workstation',
                'brand' => 'Dell Precision 3660 Tower',
                'serial' => 'CN08X23-019',
                'status' => 'Optimal',
                'lokasi' => 'Control Room PLTP Unit 5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nama' => 'Laptop Manager Area',
                'kategori' => 'Laptop',
                'brand' => 'Lenovo ThinkPad L14 Gen 4',
                'serial' => 'PF45A6B7',
                'status' => 'Optimal',
                'lokasi' => 'Kantor Manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nama' => 'Printer SCM & Kontrak',
                'kategori' => 'Printer / MFP',
                'brand' => 'Epson L6270 MFP',
                'serial' => 'X7Y6001234',
                'status' => 'Maintenance',
                'lokasi' => 'Ruang Kerja SCM & BS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nama' => 'Network Switch Cisco 48-Port',
                'kategori' => 'Network Device',
                'brand' => 'Cisco Catalyst 9300',
                'serial' => 'FOX2520S12T',
                'status' => 'Optimal',
                'lokasi' => 'Main Rack Room',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 14. Seed Arsip
        DB::table('arsip')->insert([
            [
                'id' => 1,
                'nomor' => 'MOM-01-BS',
                'nama' => 'Laporan_Bulanan_Fungsi_BS_Mei_2026.pdf',
                'kategori' => 'Laporan Bulanan',
                'tanggal' => '2026-06-01',
                'file_path' => '/storage/uploads/Laporan_Bulanan_Fungsi_BS_Mei_2026.pdf',
                'uploaded_by' => 'Pak Rinson G.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nomor' => 'SCM-CTR-12',
                'nama' => 'Kontrak_Jasa_Driver_Multi_Mandiri_Signed.pdf',
                'kategori' => 'Kontrak & SCM',
                'tanggal' => '2025-01-05',
                'file_path' => '/storage/uploads/Kontrak_Jasa_Driver_Multi_Mandiri_Signed.pdf',
                'uploaded_by' => 'Admin IT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nomor' => 'MOM-02-MTC',
                'nama' => 'MOM_KOM_Turn_Around_Unit_5_6.docx',
                'kategori' => 'MOM Rapat',
                'tanggal' => '2026-06-15',
                'file_path' => '/storage/uploads/MOM_KOM_Turn_Around_Unit_5_6.docx',
                'uploaded_by' => 'Admin IT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nomor' => 'HSSE-SOP-01',
                'nama' => 'SOP_HSSE_Evakuasi_Darurat_PGE_LHD_2026.pdf',
                'kategori: ' => 'SOP & Regulasi',
                'tanggal' => '2026-01-10',
                'file_path' => '/storage/uploads/SOP_HSSE_Evakuasi_Darurat_PGE_LHD_2026.pdf',
                'uploaded_by' => 'Admin IT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 15. Seed Upload Archive Logs
        DB::table('upload_archive')->insert([
            [
                'id' => 1,
                'filename' => 'Manual Entry: 012/PGE-LHD/BS/2025',
                'fileSize' => '-',
                'type' => 'Monitoring Kontrak (SCM)',
                'timestamp' => '2026-06-26 09:12:00',
                'rowCount' => 1,
                'uploadedBy' => 'Pak Rinson G.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
